name: Release

run-name: Create GitHub Release

on:
  push:
    branches: ['main']

concurrency:
  group: 'release'
  cancel-in-progress: true

jobs:
  get-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get version
        run: |
          version = npm pkg get version | xargs
          echo "TAG=${version}" >> $GITHUB_ENV

      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.env.TAG }}

      - name: Create Release for Tag
        uses: softprops/action-gh-release@v1
        with:
          name: '${{ github.env.TAG }}'
          tag_name: ${{ github.env.TAG }}
